#! /bin/bash

set -e

function INFO() {
    echo -e "\033[0;32m [INFO]: $*\033[0m"
}

function ERROR() {
    echo -e "\033[0;31m [ERROR]: $*\033[0m"
}

TOP_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

if [[ -z "${1}" ]]; then
    ERROR "Please enter contest id."
    exit 1
fi

contest_id="${1}"
problem_num="4"
template_name="t.cpp"

if [[ -n "${2}" ]]; then
    problem_num="${2}"
fi

if [[ -n "${3}" ]]; then
    template_name="${3}"
fi

template_path="${TOP_DIR}"/template/"${template_name}"
template_suffix=$(echo "$template_path" | awk -F "." '{print $NF}')

if [[ ! -d "${contest_id}" ]]; then
    mkdir "${contest_id}"
else
    ERROR "The corresponding directory already exists. [path=${PWD}/${contest_id}]"
    exit 0
fi

cd "${contest_id}"

i=1
for c in {a..z}; do
    if [[ $i -gt $problem_num ]]; then
        break
    fi

    current_template_path="${c}/${c}.${template_suffix}"

    mkdir "${c}"
    cp "${template_path}" "${current_template_path}"

    INFO "Template created successfully. [path=${PWD}/${current_template_path}]"

    ((i++))
done
