# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Clang Format
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "."
          exclude: "./lib"
          extensions: "h,cpp,c"
          clangFormatVersion: 13
          inplace: False

      - uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "style: clang-format changes"
