# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Deploy Doc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-doc:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Install Python dependencies
        run: |
          pip3 install -U -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Node dependencies
        run: |
          yarn

      - name: Build
        env:
          GOOGLE_ANALYTICS_KEY: G-ZJPSKKCMN9
        run: |
          yarn build-doc

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "site/*"
          target: "/var/www/dup4.cn/Leetcode"
          rm: true
